# -*- coding: utf-8 -*-
"""bucket sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z191Ts3p2Er3sJHZpVs6O7zbs0HK7HqW
"""

def bucketSort(array):
    # Step 1: Create empty buckets
    bucket = []
    for i in range(len(array)):
        bucket.append([])

    # Step 2: Insert elements into their respective buckets
    for j in array:
        index_b = int(10 * j)
        bucket[index_b].append(j)

    # Step 3: Sort the elements of each bucket
    for i in range(len(array)):
        bucket[i] = sorted(bucket[i])

    # Step 4: Get the sorted elements
    k = 0
    for i in range(len(array)):
        for j in range(len(bucket[i])):
            array[k] = bucket[i][j]
            k += 1
    return array

# Input array
array = [.42, .32, .33, .52, .37, .47, .51]

# Output
print("Input Array:")
print(array)
print("\nApplying Bucket Sort...\n")

# Call the bucketSort function
sorted_array = bucketSort(array)

# Print the sorted array
print("Sorted Array:")
print(sorted_array)

