# -*- coding: utf-8 -*-
"""jump_search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z191Ts3p2Er3sJHZpVs6O7zbs0HK7HqW
"""

import math

def jump_search(arr, x):
    n = len(arr)
    step = int(math.sqrt(n))  # Define the jump step size

    prev = 0
    print(f"Jumping to step {prev}...")
    while arr[min(step, n)-1] < x:
        prev = step
        step += int(math.sqrt(n))
        if prev >= n:
            print(f"Element {x} not found.")
            return -1
        print(f"Jumping to step {prev}...")

    while arr[prev] < x:
        prev += 1
        if prev == min(step, n):
            print(f"Element {x} not found.")
            return -1
        print(f"Checking element at index {prev}...")

    if arr[prev] == x:
        print(f"Element {x} found at index {prev}.")
        return prev

    print(f"Element {x} not found.")
    return -1

# Example Usage
arr = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
target = 17

result = jump_search(arr, target)

